<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenVisionLab.Inspection" Version="$(PackageVersion)" />
    <PackageReference Include="OpenVisionLab.Vision2D.Blob" Version="$(PackageVersion)" />
  </ItemGroup>

</Project>
